<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit3241e75c9635084ef9deaed99ab0fa0a
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'SMSGatewayMe\\Client\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'SMSGatewayMe\\Client\\' => 
        array (
            0 => __DIR__ . '/..' . '/smsgatewayme/client/lib',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit3241e75c9635084ef9deaed99ab0fa0a::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit3241e75c9635084ef9deaed99ab0fa0a::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
